# fly.toml app configuration file generated for railychat on 2023-08-05T23:56:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "railychat"
primary_region = "mad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 2
    soft_limit = 1
    memory = 1024

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
